In [1]:
import cv2
import pandas as pd
import numpy as np

#### OpenCV 기초

In [3]:
lena_img = cv2.imread('./test_img/Lenna.png')

In [4]:
lena_img

array([[[125, 137, 226],
        [125, 137, 226],
        [133, 137, 223],
        ...,
        [122, 148, 230],
        [110, 130, 221],
        [ 90,  99, 200]],

       [[125, 137, 226],
        [125, 137, 226],
        [133, 137, 223],
        ...,
        [122, 148, 230],
        [110, 130, 221],
        [ 90,  99, 200]],

       [[125, 137, 226],
        [125, 137, 226],
        [133, 137, 223],
        ...,
        [122, 148, 230],
        [110, 130, 221],
        [ 90,  99, 200]],

       ...,

       [[ 60,  18,  84],
        [ 60,  18,  84],
        [ 58,  27,  92],
        ...,
        [ 84,  73, 173],
        [ 76,  68, 172],
        [ 79,  62, 177]],

       [[ 57,  22,  82],
        [ 57,  22,  82],
        [ 62,  32,  96],
        ...,
        [ 79,  70, 179],
        [ 81,  71, 181],
        [ 81,  74, 185]],

       [[ 57,  22,  82],
        [ 57,  22,  82],
        [ 62,  32,  96],
        ...,
        [ 79,  70, 179],
        [ 81,  71, 181],
        [ 81,  74, 185]]

In [21]:
my_mat = np.zeros((500,500), np.float32)
cv2.imshow('tet',my_mat)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [22]:
my_mat = np.array([ (r+c)%100 / 100  for c in range(len(my_mat[0])) for r in range(len(my_mat))  ]).reshape(500,500)

In [23]:
my_mat

array([[0.  , 0.01, 0.02, ..., 0.97, 0.98, 0.99],
       [0.01, 0.02, 0.03, ..., 0.98, 0.99, 0.  ],
       [0.02, 0.03, 0.04, ..., 0.99, 0.  , 0.01],
       ...,
       [0.97, 0.98, 0.99, ..., 0.94, 0.95, 0.96],
       [0.98, 0.99, 0.  , ..., 0.95, 0.96, 0.97],
       [0.99, 0.  , 0.01, ..., 0.96, 0.97, 0.98]])

In [24]:
cv2.imshow('tet',my_mat)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [26]:
lena_img.shape

(512, 512, 3)

In [30]:
cv2.imshow('tet',lena_img[:,:,0])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [47]:
# BGR
test_mat = np.zeros([500,500,3], np.uint8)
test_mat[:100,:,0].fill(255)
test_mat[200:300,:,1].fill(255)
test_mat[400:500,:,2].fill(255)
test_mat[:,:100,2].fill(128)
test_mat[:,200:300,1].fill(128)
test_mat[:,400:500,0].fill(128)
cv2.imshow('tet',test_mat)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [40]:
test_mat

array([[[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       ...,

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]]

In [58]:
# 도형 그리기
test_img =np.zeros([500,500,3], np.uint8)
cv2.rectangle(test_img, (10,10), (110,110), (255,100,100), thickness = -1)
cv2.rectangle(test_img, (10,10), (110,110), (0,255,0), thickness = 1)
cv2.circle(test_img, (300,300), 20, (0,200,200))
cv2.line(test_img, (10,300), (100,300), (0,0,200), thickness=3)

cv2.putText(test_img, 'SomeHow..', (200, 100), cv2.FONT_HERSHEY_SIMPLEX, 1, (200,255,200))

points1 = np.array([[350,350], [360,410], [370,420],[450,500]], np.int32)
cv2.polylines(test_img, [points1], True, (255,100,100))

cv2.imshow('test',test_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### Geometric Transformation

In [8]:
import cv2
# Resize
lena_nearest = cv2.resize(lena_img, dsize = (600,600), interpolation = cv2.INTER_NEAREST)
lena_cubic = cv2.resize(lena_img, dsize = (600,600), interpolation = cv2.INTER_CUBIC)

cv2.imshow('nearest', lena_nearest)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.imshow('nearest', lena_cubic)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
(h, w) = lena_img.shape[:2]
(cX, cY) = (w/2, h/2)

# 회전
rot_mat = cv2.getRotationMatrix2D((cX, cY), 45,1.0)
rot_mat_0 = cv2.getRotationMatrix2D((0, 0), 45,1.0)
lena_45 = cv2.warpAffine(lena_img, rot_mat, (w,h))
lena_45_0 = cv2.warpAffine(lena_img, rot_mat_0, (w,h))

cv2.imshow('lena_45', lena_45)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.imshow('lena_45_0', lena_45_0)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
# Perspective Transform

import numpy as np

src_array = np.array([[0,0],[0,511], [511,0],[511,511]], np.float32)
dst_array = np.array([[100,100], [100,411],[411,200],[411,311]], np.float32)

per_mat = cv2.getPerspectiveTransform(src_array, dst_array)
lena_per = cv2.warpPerspective(lena_img, per_mat, (w,h))

cv2.imshow('lena_per', lena_per)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [11]:
lena_img.shape

(512, 512, 3)